print("Escape_Sequence!")
print("1\\n")
print("hello\nworld")
print("2\\t")
print("hello\tworld")
print("3\\r")
print("hello\rworld")
print("4\\b")
print("hello\bworld")
print("5\\f")
print("hello\fworld")
print("6\\v")
print("hello\vworld")
print("7\\a")
print("hello\aworld")
print("8\\Backslash")
print("hello\\world")
print("9\\Single!Quote\'")
print("hello!world\'s")
print("10\\Double!Quote\"")
print("hello!world\"s")
print("Variable")
a = "INDERJEET"
b = 21
c = "JODHPUR"
d = "BCA"
print(a,b,c,d)